Script in Registrierungsmaske auf setup umgestellt
fom-pm-se/frontend pull request #38
Opened 2023-04-18 23:03 UTC by ArthurHardCoding

closes #25 

Bitte gegencheck, ob das soweit passt.

2023-04-19 06:34 UTC, leonschbbht requested changes
Alles in allem eine gute Umsetzung, nur ein paar 'quality of life' Anmerkungen :)

2023-04-19 06:34 UTC, leonschbbht commented on src/components/RegisterForm.vue
> +const isLoading = ref(false);
isLoading war vorher ein `props`-Attribut.
Diese Attribute werden genutzt um Variablen von der Parent-Komponente in die Child-Componente zu reichen.
Wenn z.B. in LoginForm.vue (child) isLoading als prop definiert ist, kann in der Login.vue (parent) Komponente der Form folgendermaßen aufgerufen werden:

`<login-form :isLoading="...">`.

Hier müsstest du in der Composition-API die `defineProps(['foo'])`-Methode aufrufen. [Mehr Informationen](https://vuejs.org/guide/components/props.html)

2023-04-19 06:34 UTC, leonschbbht commented on src/components/RegisterForm.vue
> +const firstname = ref('');
Hier könnte man noch die TypeScript-Datentypen für bessere Lesbarkeit ergänzen:

z.B.
```
const isFormValid = ref(false as boolean);
const firstname = ref('' as string);
...
```

2023-04-19 06:34 UTC, leonschbbht commented on src/components/RegisterForm.vue
> +function validateUsername() {
Bitte Rückgabetypen angeben:

```
function validateUsername(): void {
...
}
```

2023-04-26 21:42 UTC, ArthurHardCoding commented on src/components/RegisterForm.vue
> +function validateUsername() {
bei der Funktion "onSubmit" ebenso void als Rückgabetyp angeben oder gibt es ein anderes Kennzeichen, wenn man mit Events arbeitet? (emit usw.)

2023-04-27 07:02 UTC, leonschbbht approved these changes
LGTM

2023-04-27 07:02 UTC, merged